project:
  type: default

format: 
  revealjs:
    smooth-scroll: true
    incremental: true
    slide-number: true
    #logo: images/logo.png
    footer: "Created with Quarto"
    css: styles.css
    toc: true



