project:
  type: default
  output-dir: _site

format: 
  revealjs:
    theme: [default, custom.scss]
    #smooth-scroll: true
    incremental: true
    slide-number: true
    #logo: images/logo.png
    footer: "Introduction to Quarto"
    toc: true
    toc-depth: 1



